#!/bin/bash

rm -i -r $HOME/.vim
rm -i -r $HOME/.config/nvim/init.vim
rm -i $HOME/.vimrc
rm -i $HOME/.zshrc

ln -s $HOME/git/mydotfiles/vim $HOME/.vim
ln -s $HOME/git/mydotfiles/vimrc $HOME/.vimrc

if [ -e "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
	echo "Plug for neovim already installed, skipping"
else
	echo "Installing Plug for neovim"
	curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ -d "$HOME/.oh-my-zsh" ]; then
	echo "Oh My Zsh already installed, skipping"
else
	echo "Installing Oh My Zsh"
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

if [ -d "$HOME/.oh-my-zsh/custom/themes/powerlevel9k" ]; then
	echo "Powerlevel9k already installed, skipping"
else
	echo "Installing Powerlevel9k"
	git clone https://github.com/bhilburn/powerlevel9k.git $HOME/.oh-my-zsh/custom/themes/powerlevel9k
fi

mkdir -p $HOME/.config/nvim/
ln -s $HOME/git/mydotfiles/neovim.init.vim $HOME/.config/nvim/init.vim
ln -s $HOME/git/mydotfiles/zshrc $HOME/.zshrc
